### request home
GET http://localhost:9096/

### request 1
GET http://localhost:9096/route1


### df
GET http://localhost:3000/db HTTP/1.1

###
GET http://localhost:3000/db HTTP/1.1

### request 2
POST http://localhost:3000/db HTTP/1.1
content-type: application/json

{
    "input": "hello-world!",
    "custom": "lol",
    "id": 50
}

### request 2
POST http://localhost:3000/dbs HTTP/1.1
content-type: application/json

[{ "input": "hello-world!", "id": 51 }, { "input": "hello-world!", "id": 52 